# Generated by Django 4.1.1 on 2022-09-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
